name: market_mate
description: AI-powered traditional market business platform connecting vendors with aspiring entrepreneurs.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cached_network_image: ^3.3.0
  
  # HTTP Client
  dio: ^5.4.0
  
  # Local Storage (기본적인 것만)
  shared_preferences: ^2.2.2
  
  # Location
  geolocator: ^10.1.0
  permission_handler: ^11.0.0
  
  # Image & File
  image_picker: ^1.0.4
  
  # Utils
  intl: ^0.19.0
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  # Assets (optional - 없어도 됨)
  # assets:
  #   - assets/images/
  
# Additional metadata
homepage: https://github.com/Minapak/market-mate-frontend
repository: https://github.com/Minapak/market-mate-frontend
issue_tracker: https://github.com/Minapak/market-mate-frontend/issues
