import 'package:flutter/material.dart';

const BUTTON_PRIMARY_COLOR = Color(0xFF3A98DA);

const TEXT_PRIMARY_COLOR = Color(0xFF5496D4);

const GRAY_COLOR_FONT = Color(0xFFA4A4A4);

const BLACK_COLOR_FONT = Color(0xFF25272D);

const BOTTOM_NAVI_TEXT_COLOR = Color(0xFF999999);

const PRIMARY_BACKGROUND_COLOR = Color(0xFFEFF2F4);

const INPUT_BACKGROUND_GRAY_COLOR = Color(0xFFF5F5F5);

const INPUT_BORDER_GRAY_COLOR = Color(0xFFE8E8E8);

const FIXED_WIDGET_BACKGROUNG_COLOR = Color(0xFF292929);

const SECTION_FONT_COLOR = Color(0xFF25272D);

const CATEGORY_BACKGROUND_COLOR = Color(0xFFE4F2FF);

const NAVIGATION_TEXT_COLOR = Color(0xFF3A98DA);

const COMMUNITY_CATEGORY_COLOR = Color(0xFF5B5C5F);

const BUTTON_GRAY_BORDER_COLOR = Color(0xFFF5F5F5);

const BLACK_FONT_COLOR_1C = Color(0xFF1C1C1C);

const IMAGE_UPLOAD_BUTTON_COLOR = Color(0xFFF0F0F0);

const PRIMARY_DARK_BUTTON_COLOR = Color(0xFF2E6993);

const GRAY_TEXTAREA_COLOR = Color(0xFFF9F9F9);

const GRAY_INPUT_BACKGROUND_COLOR = Color(0xFFF6F6F6);